export const GET_ANALYTICS = 'GET_ANALYTICS'
export const GET_ANALYTICS_SUCCESS = 'GET_ANALYTICS_SUCCESS'
export const GET_ANALYTICS_FAILURE = 'GET_ANALYTICS_FAILURE'
export const GET_ANALYTICS_INIT = 'GET_ANALYTICS_INIT'

export const GET_STUDENT_DETAILS = 'GET_STUDENT_DETAILS'
export const GET_STUDENT_DETAILS_SUCCESS = 'GET_STUDENT_DETAILS_SUCCESS'
export const GET_STUDENT_DETAILS_FAILURE = 'GET_STUDENT_DETAILS_FAILURE'
export const GET_STUDENT_DETAILS_INIT = 'GET_STUDENT_DETAILS_INIT'

export const GET_DRIVE_DETAILS = 'GET_DRIVE_DETAILS'
export const GET_DRIVE_DETAILS_SUCCESS = 'GET_DRIVE_DETAILS_SUCCESS'
export const GET_DRIVE_DETAILS_FAILURE = 'GET_DRIVE_DETAILS_FAILURE'
export const GET_DRIVE_DETAILS_INIT = 'GET_DRIVE_DETAILS_INIT'

export const ADD_STUDENT_DETAILS = 'ADD_STUDENT_DETAILS'
export const ADD_STUDENT_DETAILS_SUCCESS = 'ADD_STUDENT_DETAILS_SUCCESS'
export const ADD_STUDENT_DETAILS_FAILURE = 'ADD_STUDENT_DETAILS_FAILURE'
export const ADD_STUDENT_DETAILS_INIT = 'ADD_STUDENT_DETAILS_INIT'

export const ADD_DRIVE_DETAILS = 'ADD_DRIVE_DETAILS'
export const ADD_DRIVE_DETAILS_SUCCESS = 'ADD_DRIVE_DETAILS_SUCCESS'
export const ADD_DRIVE_DETAILS_FAILURE = 'ADD_DRIVE_DETAILS_FAILURE'
export const ADD_DRIVE_DETAILS_INIT = 'ADD_DRIVE_DETAILS_INIT'

export const UPDATE_STUDENT_DETAILS = 'UPDATE_STUDENT_DETAILS'
export const UPDATE_STUDENT_DETAILS_SUCCESS = 'UPDATE_STUDENT_DETAILS_SUCCESS'
export const UPDATE_STUDENT_DETAILS_FAILURE = 'UPDATE_STUDENT_DETAILS_FAILURE'
export const UPDATE_STUDENT_DETAILS_INIT = 'UPDATE_STUDENT_DETAILS_INIT'

export const UPDATE_DRIVE_DETAILS = 'UPDATE_DRIVE_DETAILS'
export const UPDATE_DRIVE_DETAILS_SUCCESS = 'UPDATE_DRIVE_DETAILS_SUCCESS'
export const UPDATE_DRIVE_DETAILS_FAILURE = 'UPDATE_DRIVE_DETAILS_FAILURE'
export const UPDATE_DRIVE_DETAILS_INIT = 'UPDATE_DRIVE_DETAILS_INIT'